import type { Metadata } from "next";
import { Inter,Roboto,Lora } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils"



const fontInter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["400", "700"],
})

const fontRoboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: ["400", "500", "700"],
})

const fontLora = Lora({
  subsets: ["latin"],
  variable: "--font-lora",
  weight: ["400", "700","500"],
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {

  return (
    <html lang="en">
      <body className={cn(fontInter.variable,fontRoboto.variable,fontLora.className)}>
        <nav>Root laut nav</nav>
        <div className="border-5 border m-3">
         {children}
        </div>
        <footer>Home Footer</footer>
      </body>
    </html>
  );
}
