import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Inter as FontSans,  Roboto  , Lora  } from "next/font/google"
import { cn } from "@/lib/utils"
import "./globals.css";
import Providers from "@/providers/Provider";

const fontInter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["400", "700"], // Specify weights for Inter
})

const fontRoboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: ["400", "500", "700"], // Specify weights for Roboto
})

const fontLora = Lora({
  subsets: ["latin"],
  variable: "--font-lora",
  weight: ["400", "700"], // Specify weights for Lora
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
    <html lang="en">
      <body className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontInter.variable,
          fontRoboto.variable,
          fontLora.variable,
        )}>
          {children}
        </body>
    </html>
    </Providers>
  );
}
